config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :events
  resources :employees
  resources :shifts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  
  get 'restrictions' => 'restrictions#index'

  get 'dashboard' => 'dashboard#index'

  post '/hours', :controller=>'shifts', :action=>'hours'
  
  post '/search', :controller=>'shifts', :action=>'search'
  get '/search', :controller=>'shifts', :action=>'search'

  devise_for :users
  root to: 'home#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div>
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">DASHBOARD</h3>

<div class="flex flex-row justify-center items-center">
    <div class="flex space-x-10 pt-10">

      <div class="py-12">
        <div class="bg-white pt-4 p-7 rounded-xl space-y-6 overflow-hidden center transition-all duration-500 transform hover:-translate-y-6 hover:scale-105 shadow-xl hover:shadow-2xl cursor-pointer">

            <h1 class="text-4xl text-center font-bold">Shifts</h1>
            <ul class="text-center">
              <li class="p-2">Access the calendar and all other shifts related tasks</li>
              <br>
              <%= link_to 'GO', shifts_path, class: "mt-8 mb-4 py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200" %>
            </ul>
        </div>
      </div>

      <div class="py-12">
        <div class="bg-white pt-4 p-7 rounded-xl space-y-6 overflow-hidden center transition-all duration-500 transform hover:-translate-y-6 hover:scale-105 shadow-xl hover:shadow-2xl cursor-pointer">

            <h1 class="text-4xl text-center font-bold">Employees</h1>
            <ul class="text-center">
                <li class="p-2">See your employees, edit them and add new ones</li>
                <br>
                <%= link_to 'GO', employees_path, class: "mt-8 mb-4 py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200" %>
              </ul>
        </div>
      </div>

      <div class="py-12">
      <div class="bg-white pt-4 p-7 rounded-xl space-y-6 overflow-hidden center transition-all duration-500 transform hover:-translate-y-6 hover:scale-105 shadow-xl hover:shadow-2xl cursor-pointer">

          <h1 class="text-4xl text-center font-bold">Restrictions</h1>
          <ul class="text-center">
              <li class="p-2">Take a look at what restrictions are currently in place</li>
              <br>
              <%= link_to 'GO', restrictions_path, class: "mt-8 mb-4 py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200" %>
            </ul>
      </div>
    </div>

      <div class="py-12">
      <div class="bg-white pt-4 p-7 rounded-xl space-y-6 overflow-hidden center transition-all duration-500 transform hover:-translate-y-6 hover:scale-105 shadow-xl hover:shadow-2xl cursor-pointer">

          <h1 class="text-4xl text-center font-bold">Events</h1>
          <ul class="text-center">
              <li class="p-2">Check out events in your nearest city that may effect your staff needs</li>
              <br>
              <%= link_to 'GO', events_path, class: "mt-8 mb-4 py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200" %>
          </ul>
      </div>
    </div>

  </div>
</div>