config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :events
  resources :employees
  resources :shifts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  
  get 'restrictions' => 'restrictions#index'

  get 'dashboard' => 'dashboard#index'

  post '/hours', :controller=>'shifts', :action=>'hours'
  
  post '/search', :controller=>'shifts', :action=>'search'
  get '/search', :controller=>'shifts', :action=>'search'

  devise_for :users
  root to: 'home#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true, length: {maximum: 75}
  validates :position, presence: true, length: {maximum: 25}
  validates :availability, presence: true, length: {maximum: 50}
  belongs_to :user
end

app/controllers/employees_controller.rb
require 'file_writer'

class EmployeesController < ApplicationController
  
  require 'employee_decorator'

  before_action :authenticate_user!
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = current_user.employees.all
  end

  # GET /employees/1 or /employees/1.json
  def show
    
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)
    @employee.user_id = current_user.id

    e = BasicEmployee.new(@employee.name, @employee.position, @employee.availability)

    if params[:position].to_s.include?('Manager') || params[:position].to_s.include?('Supervisor') || params[:position].to_s.include?('Head')
      e = ManagementEmployee.new(e)
    end

    @text = "A new employee was added: " + e.details
    logger = FileWriter.instance
    logger.logInformation(@text)
    

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end

    e = BasicEmployee.new(@employee.name, @employee.position, @employee.availability)

    if params[:position].to_s.include?('Manager') || params[:position].to_s.include?('Supervisor') || params[:position].to_s.include?('Head')
      e = ManagementEmployee.new(e)
    end

    # The error i got from using this line: uninitialized constant ActiveRecord::Observer
    # observer = EmployeeObserver.instance
    # observer.after_update(e)

  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :position, :availability, :user_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employees_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
  <%= image_tag "hands.jpg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-darker text-2xl mb-6">It looks like you haven't added any employees yet</h1>
  <%= link_to "ADD EMPLOYEE", new_employee_path, class: "py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200"  %>
</div>

app/views/employees/_employees_landing.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">EMPLOYEES</h3>


<%= link_to 'Add a new employee', new_employee_path, class: "tab flex items-center"%> 
<%= link_to "#all-employees", class: "tab flex items-center" do %>
  All employees
<% end %>


<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Position
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Availability
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              </th>
              
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">


          <% employees.each do |employee| %>

            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= link_to employee.name, employee %> </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= employee.position %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm text-gray-500"><%= employee.availability %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= link_to 'Edit', edit_employee_path(employee) %>
              </td>

              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>

            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
       
    </div> 
  </div>
</div>

app/views/employees/_form.html.erb
<div class="flex flex-row justify-center items-center">
<div class="p-10 bg-white border border-grey-light rounded">
<%= form_with(model: employee, local: true, class: "employee-form") do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="mb-4">Employee Information</h3>

  <div class="mb-6">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input", required: true %>
  </div>

  <div class="mb-6">
  <%= form.label :position, class: "label" %>
  <%= form.text_field :position, class: "input", required: true %>
</div>

<div class="mb-6">
<%= form.label :availability, class: "label" %>
<%= form.text_field :availability, class: "input", required: true %>
</div>

<div class="flex flex-row justify-center items-center">
<%= form.submit class: "py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200" %>
</div>
  
<% end %>
</div>
</div>

app/views/employees/edit.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">EDIT EMPLOYEE</h3>

<%= render 'form', employee: @employee %>

app/views/employees/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.employees.any? %>
    <%= render "employees_cta" %>
  <% else %>
    <%= render "employees_landing",  employees: @employees %>
  <% end %>
</div 

app/views/employees/new.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">NEW EMPLOYEE</h3>


<div class="max-w-lg m-auto px-4">
  <br>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="max-w-md my-5 m-auto p-6 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
               <h1 class="font-bold"><%= @employee.name %></h1><br>
   <div class="mb-5 flex items-center justify-between">

      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo">
        Position <br>
        <span class="font-bold text-indigo-600"><%= @employee.position %></span>
      </p>
      <div class="border-t-2 border-indigo-light border-dashed h-1 flex-1"></div>
      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo">
        Availability <br> <span class="font-bold text-indigo-600"><%= @employee.availability %></span>

      </p>

    </div>    
    <%= link_to 'Back', employees_path %>

</div>
  