config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :events
  resources :employees
  resources :shifts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  
  get 'restrictions' => 'restrictions#index'

  get 'dashboard' => 'dashboard#index'

  post '/hours', :controller=>'shifts', :action=>'hours'
  
  post '/search', :controller=>'shifts', :action=>'search'
  get '/search', :controller=>'shifts', :action=>'search'

  devise_for :users
  root to: 'home#index'
end

app/models/event.rb
class Event < ApplicationRecord
  validates :city, presence: true, length: {maximum: 75}
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user
  before_action :set_event, only: %i[ show edit update destroy ]

    # GET /events or /events.json
    def index
      @events = current_user.events.all

      require 'net/http'
      require 'json'

      if !current_user.events.empty?
        @event_city = @events[0].city

        @url = "https://app.ticketmaster.com/discovery/v2/events.json?city=#{@event_city}&apikey=QsWcrQFrgyG0ZJHKkHZ85ugZsxBsBCLf"
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @output = JSON.parse(@response)

        if @output.empty?
          @final_output = "Error"
        else 
          @final_output = @output
        end
    end

    end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:city, :user_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
  <%= image_tag "schedule.svg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-darker text-2xl mb-6">It looks like you haven't added any events yet</h1>
  <%= link_to "ADD EVENT", new_event_path, class: "py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200"  %>
</div>

app/views/events/_events_landing.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">EVENTS</h3>

<div class="bg-white p-5 border rounded">
  <div id="all-events" class="tab-panel active">

     <% events.each do |event| %>
        <div class="flex flex-wrap items-center justify-start p-2 border-b border-grey-light mb-6">
          <div class="flex-1 flex justify-between">
            <h2 class="m-2 flex items-center p-4 bg-white border-2 border-gray-200 rounded-lg shadow-sm dark:bg-gray-800">Know when you should schedule more staff on due to possible crowds in town for these events</h2>
            <p class="m-2 flex items-center p-4 bg-white border-2 border-gray-200 rounded-lg shadow-sm dark:bg-gray-800"> Showing events for <%= event.city %></p>   
            <p class="m-2 flex items-center p-4 bg-white border-2 border-gray-200 rounded-lg shadow-sm dark:bg-gray-800"> <%= link_to 'Click here to change the city', edit_event_path(event) %> </p>
          </div>
        </div>
     <% end %>
  </div>

<section class="container px-6 py-4 mx-auto">
  <div class="grid gap-6 mb-8 md:grid-cols-1 lg:grid-cols-2">
      <% @final_output["_embedded"]["events"].each do |event| %>
     <div class="flex items-center p-4 bg-white border-2 border-gray-200 rounded-lg shadow-sm dark:bg-gray-800">
        <img alt="mountain" class="w-40 rounded-md border-2 border-gray-300" src=<%= event["images"][0]["url"] %> />

         <div id="body" class="flex flex-col ml-5">

            <h4 id="name" class="text-xl font-semibold mb-2 text-indigo-700">
              <%= event["name"] %></h4>
              <table id="datetime" class="text-gray-800 mt-2">

              <tr>
                  <td class="font-semibold pr-3">Date</td>
                  <td> <%= event["dates"]["start"]["localDate"] %>  </td>
              </tr>

              <tr>
                <td class="font-semibold pr-3">Time</td>
                <td> <%= event["dates"]["start"]["localTime"] %>  </td>
              </tr>
          </table>
         </div>
    </div>
    <% end %>
  </div>
 
</div>
</section>

app/views/events/_form.html.erb
<div class="flex flex-row justify-center items-center">
<div class="p-10 bg-white border border-grey-light rounded">
<%= form_with(model: event, local: true, class: "event-form") do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="mb-4">Event Information</h3>

  <div class="mb-6">
    <%= form.label :city, class: "label" %>
    <%= form.text_field :city, class: "input" %>
  </div>

  <div class="flex flex-row justify-center items-center">
    <%= form.submit class: "py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200" %>
  </div>
  <% end %>
</div>
</div>

app/views/events/edit.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">EDIT CITY</h3>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.events.any? %>
    <%= render "events_cta" %>
  <% else %>
    <%= render "events_landing",  events: @events %>
  <% end %>
</div 

app/views/events/new.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">ADD CITY</h3>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="flex flex-row justify-center items-center">

<div class="max-w-md my-5 m-auto p-10 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
      <p class="border-2 py-3 mb-5 px-4 border-indigo rounded-full text-sm text-indigo">
        City <br>
        <span class="font-bold  text-indigo-600"><%= @event.city %></span>
      </p>
   
    <%= link_to 'Back', events_path %>
    </div> 
  
</div>
  