config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :events
  resources :employees
  resources :shifts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  
  get 'restrictions' => 'restrictions#index'

  get 'dashboard' => 'dashboard#index'

  post '/hours', :controller=>'shifts', :action=>'hours'
  
  post '/search', :controller=>'shifts', :action=>'search'
  get '/search', :controller=>'shifts', :action=>'search'

  devise_for :users
  root to: 'home#index'
end

app/models/shift.rb
class Shift < ApplicationRecord

  validates :name, presence: true, length: {maximum: 75}
  validates :start_time, presence: true
  validates :end_time, presence: true

  belongs_to :user

  searchkick 

end

app/controllers/shifts_controller.rb
require 'working_hours_ireland'

class ShiftsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shift, only: %i[ show edit update destroy ]

  # GET /shifts or /shifts.json
  def index
    @shifts = current_user.shifts.all    

    search = params[:term].present? ? params[:term] : '*'
    @shifts = if search
      Shift.search(search)
    else 
      @shifts = current_user.shifts.all
    end
  end

  def search 
    search = params[:term].present? ? params[:term] : '*'
    @shifts = if search
      Shift.search(search)
      redirect_to request.referrer
   
    else 
      @shifts = current_user.shifts.all
      redirect_to request.referrer

    end
  end

  def hours
    @input = params[:search]
    @result = Hours.run(@input)
    flash[:notice] = @result
    redirect_to request.referrer
  end

  # GET /shifts/1 or /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts or /shifts.json
  def create
    @shift = Shift.new(shift_params)
    @shift.user_id = current_user.id

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: "Shift was successfully added." }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1 or /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: "Shift was successfully updated." }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1 or /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:name, :start_time, :end_time, :user_id)
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_all_shifts.html.erb
<div class="tab flex items-center">
  All shifts
</div>

<div class="flex justify-center items-center">

<h1>Only want to see a specific employees shifts? Type their name in here!</h1>
</div>

<div class="flex justify-center items-center p-5">
<br>
<div>
<%= form_tag shifts_path, class: " mb-4 py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200", role: 'search', method: :get do |f| %>
  
  <table>
    <tr>
      <td>  <%= text_field_tag :term, params[:term], class: 'input' %>
      </td>

      <td>
      <%= button_tag "Search", class: " py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200", name: nil %>

      </td>
    </tr>
  </table>
  </div>

  <% end %>
</div>

<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Start time
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                End time
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">


          <% shifts.each do |shift| %>

            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= link_to shift.name, shift %> </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= readable_time(shift.start_time) %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm text-gray-500"><%= readable_time(shift.end_time) %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= link_to 'Edit', edit_shift_path(shift) %>
              </td>

              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>

            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
       
    </div> 
  </div>
</div>

app/views/shifts/_calendar.html.erb
<%= month_calendar events: shifts do |date, shifts| %>
  <%= date.day %>
  <% shifts.each do |shift| %>
    <div>
      <%= link_to shift.name, shift, class: "text-xs text-indigo-500"%>
    </div>
  <% end %>
<% end %>

app/views/shifts/_form.html.erb
<div class="p-5 bg-white border border-grey-light rounded">
<%= form_with(model: shift, local: true, class: "shift-form") do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-6">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input", required:true %>
  </div>

  <div class="mb-6">
    <%= form.label :start_time, class: "label" %>
    <div class="flex items-center justify-between max-w-l">
      <%= form.datetime_select :start_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-2 w-40" } %>
    </div>
  </div>

  <div class="field">
    <%= form.label :end_time, class: "label" %>
    <div class="flex items-center justify-between max-w-lg">
      <%= form.datetime_select :end_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-2" } %>
    </div>
  </div>

  <div class="flex flex-row justify-center items-center">
    <%= form.submit class: "mt-8 py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200" %>
  </div>
  
<% end %>
</div>

app/views/shifts/_recommended_hours.html.erb
<div class="p-5 bg-white border border-grey-light rounded">
<h1>Would you like some recommendations on how many hours your employees should be working? </h1>
  <%= form_tag "/hours" do %>
    <select name="search" id="search">
      <option></option>
      <option value="1">Full Time</option>
      <option value="2">Part Time</option>
      <option value="3">Under 18s</option>
    </select>
    <%= submit_tag "OK" %>
  <% end %>
  </div>
</div>

app/views/shifts/_search.html.erb
HI

app/views/shifts/_shifts_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
  <%= image_tag "calendar.jpg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-darker text-2xl mb-6">It looks like you haven't scheduled any shifts yet</h1>
  <%= link_to "NEW SHIFT", new_shift_path, class: "py-2 px-14 rounded-full bg-green-600 text-white tracking-widest hover:bg-green-500 transition duration-200"%>
</div>

app/views/shifts/_shifts_landing.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">SHIFTS</h3>

<%= link_to 'Add a new shift', new_shift_path, class: "tab flex items-center"%> 
<div class="tab flex items-center ">
  Calendar
</div>


<div class="bg-white p-10 border rounded">
  <div id="all-shifts" class="tab-panel">

     <% shifts.each do |shift| %>
        <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
          <div class="flex-1 flex justify-between">
            <div>
              <%= link_to shift.name, shift, class: "link mr-4" %>
            </div>
            <div>
              <%= readable_time(shift.start_time) %> &ndash;
              <%= readable_time(shift.end_time) %>
            </div>
          </div>
        </div>

        <%= link_to "Cancel Shift", shift, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-destroy ml-4" if admin? %>
     <% end %>
  </div>

  <div id="calendar" class="tab-panel active">
    <h2>Calendar</h2>
    <div id="shift-calendar">
      <%= render "calendar", shifts: shifts  %>
    </div>
  </div>
</div>

app/views/shifts/edit.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">EDIT SHIFT</h3>

<div class="max-w-lg m-auto px-4">
<%= render 'form', shift: @shift %>
</div>

app/views/shifts/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.shifts.any? %>
    <%= render "shifts_cta" %>
  <% else %>
    <%= render "shifts_landing",  shifts: @shifts %>
    <%= render "all_shifts", shifts: @shifts %>
  <% end %>
</div>

app/views/shifts/new.html.erb
<h3 class="text-2xl tracking-widest text-green-600 text-center p-5">NEW SHIFT</h3>

<div class="max-w-lg m-auto ">
  <br>

  <%= render 'form', shift: @shift %>

  <%= render "recommended_hours" %>

app/views/shifts/show.html.erb
<div class="max-w-md my-5 m-auto p-6 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
               <h1 class="font-bold"><%= @shift.name %></h1><br>
      <%= link_to "Cancel shift", shift_path(@shift), method: :delete, data: { confirm: "Are you sure you want to cancel? "}, class: "btn btn-destroy" if admin? %>
   <div class="mb-5 flex items-center justify-between">

      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo">
        Start time <br>
        <span class="font-bold text-indigo-600"><%= readable_time(@shift.start_time) %></span>
      </p>
      <div class="border-t-2 border-indigo-light border-dashed h-1 flex-1"></div>
      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo">
        End time <br> <span class="font-bold text-indigo-600"><%= readable_time(@shift.end_time) %></span>
      </p>
    </div>
    <%= link_to 'Back', shifts_path %>
</div>